feature:
- branch: ['^feat','^feature','feature']

tests:
- changed-files:
  - any-glob-to-any-file: 'test/*'

documentation:
- changed-files:
  - any-glob-to-any-file: 'documents/*'

workflows:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/*'

'area:cli':
- changed-files:
  - any-glob-to-any-file: 'src/Bison.CLI/*'

'area:SimpleDB':
- changed-files:
  - any-glob-to-any-file: 'src/SimpleDB/*'
