# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Bison.sln
      
    - name: Build
      run: dotnet build Bison.sln --no-restore

    - name: Start API for end-to-end tests
      run: |
        # Starts the WebAPI database. Project has already been built, so we're executing the build-file directly.
        # '> api.log' means we'll save the normal terminal output into a temporary file api.log, and '... 2>&1' means we'll also send stream 2 (errors) into stream 1 (normal output), ie. we're merging errors and normal output into the same file. This is necessary for debugging.

        dotnet src/WebApiDB.CSVDBService/bin/Debug/net8.0/WebApiDB.CSVDBService.dll --urls http://localhost:5189 > api.log 2>&1 &

        for i in $(seq 1 30); do
          # After the API has started, we're running a loop 30 times. In this loop we'll try to call the /observations endpoint once every second.
          # If /observations returns a value it means the API has started and we'll exit with exitcode 0 (0 = success).
          # If the API has failed 30 times we'll exit with exitcode 1 (1 = failure) and print the log (contents of api.log)

          curl -s http://localhost:5189/observations -o /dev/null && { echo "API is ready"; exit 0; }
          sleep 1
        done
        echo "API failed to start"; cat api.log; exit 1
      
    - name: Test
      run: dotnet test Bison.sln --no-build --verbosity normal
